import { defineField, defineType } from "sanity";

const categories = [
  "Cost Savings",
  "Electricity",
  "Gas",
  "Insights",
  "Property Owners",
  "Submetering",
  "Tenants & Renters",
  "Thermal & HVAC",
  "Water",
];

export const blogPost = defineType({
  name: "blogPost",
  title: "Blog post",
  type: "document",
  orderings: [
    {
      title: "Publication date, newest",
      name: "publishedAtDesc",
      by: [{ field: "publishedAt", direction: "desc" }],
    },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: "slug",
      title: "URL slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "excerpt",
      title: "Summary / meta description",
      type: "text",
      rows: 3,
      description: "Used on the blog index and as the default search description.",
      validation: (rule) => rule.required().min(70).max(180),
    }),
    defineField({
      name: "seoTitle",
      title: "SEO title override",
      type: "string",
      description: "Optional. Aim for 50–60 characters including Axis Meter.",
      validation: (rule) => rule.max(70),
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "string",
      options: { list: categories, layout: "dropdown" },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tags",
      title: "Tags",
      type: "array",
      options: { layout: "tags" },
      of: [{ type: "string" }],
    }),
    defineField({
      name: "publishedAt",
      title: "Published at",
      type: "datetime",
      initialValue: () => new Date().toISOString(),
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "updatedAt",
      title: "Content updated at",
      type: "datetime",
    }),
    defineField({
      name: "featuredImage",
      title: "Featured image",
      type: "image",
      options: { hotspot: true },
      fields: [
        defineField({ name: "alt", title: "Alternative text", type: "string" }),
      ],
    }),
    defineField({
      name: "featuredImageUrl",
      title: "External featured image URL",
      type: "url",
      description: "Used for migrated or Outrank images that are not uploaded to Sanity.",
    }),
    defineField({
      name: "body",
      title: "Article",
      type: "blockContent",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "author",
      title: "Author",
      type: "string",
      initialValue: "Axis Meter Solutions",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "readingTimeMinutes",
      title: "Reading time in minutes",
      type: "number",
      validation: (rule) => rule.integer().positive(),
    }),
    defineField({
      name: "source",
      title: "Original source",
      type: "string",
      options: {
        list: [
          { title: "Created in Sanity", value: "sanity" },
          { title: "Imported from Axis", value: "local" },
          { title: "Generated by Outrank", value: "outrank" },
        ],
      },
      initialValue: "sanity",
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "outrankId", title: "Outrank article ID", type: "string" }),
    defineField({
      name: "sourceHtml",
      title: "Original imported HTML",
      type: "text",
      rows: 5,
      description: "Recovery copy of imported content. The visual editor uses Article above.",
      hidden: ({ document }) => document?.source === "sanity",
    }),
    defineField({
      name: "noIndex",
      title: "Prevent search indexing",
      type: "boolean",
      initialValue: false,
    }),
  ],
  preview: {
    select: {
      title: "title",
      category: "category",
      publishedAt: "publishedAt",
      media: "featuredImage",
    },
    prepare: ({ title, category, publishedAt, media }) => ({
      title,
      subtitle: [category, publishedAt?.slice(0, 10)].filter(Boolean).join(" · "),
      media,
    }),
  },
});
